### ISSUE TITLE
"pip wheel aegis" failing to build wheel

### ISSUE THREAD

**Issue by Kejikus** [mgurdal/aegis#27]
**Description**
Wheel of this package could not be built on the clear virtualenv without `aiohttp` and `jwt` installed

**To Reproduce**
1. On *nix machine:
2. Make new virtualenv
3. Activate it
4. `mkdir /wheels && cd /wheels`
5. `pip wheel aegis=1.0.0 -d .`
6. See error about `aiohttp`:
```
Collecting aegis==1.0.0
   Downloading https://files.pythonhosted.org/packages/90/67/e1af6100994a98f6e3729288b34bf8c65d8c837d7c50139cd76587b4c132/aegis-1.0.0.tar.gz
     ERROR: Command errored out with exit status 1:
      command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ctnwhnrv/aegis/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ctnwhnrv/aegis/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-ctnwhnrv/aegis/pip-egg-info
          cwd: /tmp/pip-install-ctnwhnrv/aegis/
     Complete output (9 lines):
     Traceback (most recent call last):
       File "<string>", line 1, in <module>
       File "/tmp/pip-install-ctnwhnrv/aegis/setup.py", line 12, in <module>
         from aegis import __version__
       File "/tmp/pip-install-ctnwhnrv/aegis/aegis/__init__.py", line 18, in <module>
         from .authenticators.base import BaseAuthenticator
       File "/tmp/pip-install-ctnwhnrv/aegis/aegis/authenticators/base.py", line 5, in <module>
         from aiohttp import web
     ModuleNotFoundError: No module named 'aiohttp'
```
7. Run `pip install aiohttp`
8. Repeat `pip wheel aegis==1.0.0 -d .`
9. See error about `jwt`:
```
Collecting aegis==1.0.0
   Downloading https://files.pythonhosted.org/packages/90/67/e1af6100994a98f6e3729288b34bf8c65d8c837d7c50139cd76587b4c132/aegis-1.0.0.tar.gz
     ERROR: Command errored out with exit status 1:
      command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-bc581qq9/aegis/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-bc581qq9/aegis/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-bc581qq9/aegis/pip-egg-info
          cwd: /tmp/pip-wheel-bc581qq9/aegis/
     Complete output (9 lines):
     Traceback (most recent call last):
       File "<string>", line 1, in <module>
       File "/tmp/pip-wheel-bc581qq9/aegis/setup.py", line 12, in <module>
         from aegis import __version__
       File "/tmp/pip-wheel-bc581qq9/aegis/aegis/__init__.py", line 19, in <module>
         from .authenticators.jwt import JWTAuth
       File "/tmp/pip-wheel-bc581qq9/aegis/aegis/authenticators/jwt.py", line 5, in <module>
         import jwt
     ModuleNotFoundError: No module named 'jwt'
```

**Expected behavior**
`pip wheel aegis==1.0.0` should build and store wheel in the `/wheels` directory.

**Environment**
 - OS: Any *nix machine (mine was Docker python:3.8-alpine)
 - Assuming that this *nix machine has all the needed build tools and python 3.6 or higher so installing aegis with deps pre-installed would be successful

**Comment by mgurdal** [comment]
It turns out that the `setup.py` was using the `aegis/__init__.py` directly, in order to get the`__version__`.   Direct import has caused it to try to import 3rd party tools that are not yet installed on the system.

I have fixed the issue by defining a helper function to parse the version number from the file.

I have tested the wheel build with `python setup.py bdist_wheel` and `pip wheel .` commands on a python:3.7(3.7.4) Docker and macOS Mojave(10.14.4) environment.
